### ISSUE TITLE
Any plans to have ffi to Rust itself?

### ISSUE THREAD

**Issue by ctzurcanu** [maidsafe/ffi_utils#24]
Here I see mostly Java interfacing...

**Comment by nbaksalyar** [comment]
>ffi to Rust itself

We have some utils for using FFI in Rust, e.g.: https://github.com/maidsafe/ffi_utils/blob/master/src/test_utils.rs
What use case do you have in mind for this?

**Comment by ctzurcanu** [comment]
I have to say: I am pleasantly surprised: I thought Rust does not have a stable enough ABI spec to make calling of Rust funcs possible. 
We were in the process of planning to implement dType for Rust https://github.com/pipeos-one/dType 
Any advice greatly appreciated.

**Comment by m-cat** [comment]
Hey @ctzurcanu, thanks for reaching out and sorry for the late reply. Would like to give you some help to get you started, if you still need it, but need to know what your use case is. We wrote `ffi_utils` primarily for our FFI strategy in [`safe_client_libs`](https://github.com/maidsafe/safe_client_libs) so it may not be exactly what you need. You can read about the problems this crate solves [here](https://github.com/maidsafe/ffi_utils/wiki) and read about its usage in SCL [here](https://github.com/maidsafe/safe_client_libs/wiki/FFI-overview). Let me know if anything is not clear in those docs. There is also the [ffi-support](https://docs.rs/ffi-support/0.3.5/ffi_support/) crate by Mozilla which has very nice documentation, but doesn't support all the use cases we required for SCL. I would elaborate more but I'm not sure if you still need our help here, and I apologize again for missing your question earlier.
